services:
  kafka-docker-service:
    image: confluentinc/cp-kafka:8.0.0
    hostname: kafka-container-hostname
    container_name: kafka-container-name
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_KRAFT_MODE: "true"  # this enables KRaft mode in Kafka
      KAFKA_PROCESS_ROLES: controller,broker 
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"  
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data  # directory INSIDE the container
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_LOG_RETENTION_HOURS: 24  # keep logs for 1 day
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0  # for consumer rebalancing
      CLUSTER_ID: "krg8c13fSPO0v7iEWRRDWg"
    volumes:
      - ./kafka/data:/var/lib/kafka/data # the location of the volume is awkward for now