name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push (multi-arch)
      uses: docker/build-push-action@v4
      with:
        context: . # this is build context when we manual build locally
        file: docker/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64 # for both amd and arm cpu archi
        tags: docker.io/simple-api-in-go:${{ github.ref_name }}
